[package]
name = "dbrs"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5"
bimap = "0.6"
bitflags = { version = "2.8", features = ["bytemuck"] }
# bytemuck = { version = "1.21", features = ["derive"] }
pest = "2.8"
pest_derive = "2.8"
